name: alashry
description: A new Flutter project for inventory management.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  cupertino_icons: ^1.0.2
  pdf: ^3.10.7
  printing: ^5.11.1
  path_provider: ^2.1.1
  fl_chart: ^0.65.0
  intl: ^0.18.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon_3.png"

flutter:
  uses-material-design: true

  # Add fonts
  fonts:
    - family: NotoSansArabic
      fonts:
        - asset: assets/fonts/NotoSansArabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansArabic-Bold.ttf
          weight: 700

  # Add assets folder
  assets:
    - assets/fonts/
    - assets/images/
