// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5fWl0aZBgJcQvqnzWDhsB8w7L5qT8HN4',
    appId: '1:103671618212:web:d9deb952a0c75a0612e431',
    messagingSenderId: '103671618212',
    projectId: 'elashry-dffd9',
    authDomain: 'elashry-dffd9.firebaseapp.com',
    storageBucket: 'elashry-dffd9.firebasestorage.app',
    measurementId: 'G-W0GBH7Z97Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARSgxr1-5llzTv5vBUfQLJVgpnbkhF8bM',
    appId: '1:103671618212:android:4b90148a0fa4642912e431',
    messagingSenderId: '103671618212',
    projectId: 'elashry-dffd9',
    storageBucket: 'elashry-dffd9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt5yNC5G3RveY40AUyds7wSTTCImUxCsY',
    appId: '1:103671618212:ios:2da0964a98147f6312e431',
    messagingSenderId: '103671618212',
    projectId: 'elashry-dffd9',
    storageBucket: 'elashry-dffd9.firebasestorage.app',
    iosBundleId: 'com.example.alashry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt5yNC5G3RveY40AUyds7wSTTCImUxCsY',
    appId: '1:103671618212:ios:2da0964a98147f6312e431',
    messagingSenderId: '103671618212',
    projectId: 'elashry-dffd9',
    storageBucket: 'elashry-dffd9.firebasestorage.app',
    iosBundleId: 'com.example.alashry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5fWl0aZBgJcQvqnzWDhsB8w7L5qT8HN4',
    appId: '1:103671618212:web:e3c7024e59c066c912e431',
    messagingSenderId: '103671618212',
    projectId: 'elashry-dffd9',
    authDomain: 'elashry-dffd9.firebaseapp.com',
    storageBucket: 'elashry-dffd9.firebasestorage.app',
    measurementId: 'G-ZF5T5D4LF2',
  );
}
